---
nginx:
  name: nginx
  port: 8080
  upstream:
    type: ppa
    upstream: "ppa:nginx"
    version: "1.15.2"
  configure:
    files:
      conf: "application/conf/nginx/"
      svc: "nginx.service"
  version:
    cmd: "nginx --version 2>&1"
    args: ""
  system:
    os: "{{ ansible_os }}"
    arch: "{{ ansible_arch }}"
    paths:
      svc: "/lib/systemd/system/"
      bin: "/usr/sbin"
      log: "/var/log"
      pid: "/var/run"
      conf: "/etc/"
      data: "/var/www/html"
    user:
      name: www-data
      uid: 33
    group: 
      name: www-data
      gid: 33
